import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Glass Monkey </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://glasmonkey.dev">Home</a>
        </h1>

  
        <div className={styles.grid}>
          TBD
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/glassmonekey"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
          　(c)glassmonkey
          </span>
        </a>
      </footer>
    </div>
  )
}
